#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -u

# Set LOG=anything to debug iTerm...
readonly LOG

_main() {
  local filepath="$1"
  local line_number="${2:-}"
  local column_number="${3:-}"

  _code "${filepath}"
}

_code() {
  _exec /usr/local/bin/code "$@"
}

_exec() {
  _log "$@"
  exec "$@" 2>&1 &
}

_log() {
  if [[ -n "${LOG:-}" ]]; then
    echo "$*" >> "$HOME/.editor.log"
  fi
}

_log 'Arguments:' "$@"
_main "$@"